### PR TITLE
Dev nextcloud weblet

### PR DESCRIPTION
**Pull request by Mik-TF**
Nextcloud Playground documentation for the new nextcloud weblet.

For more information, read this [PR](https://github.com/threefoldtech/tfgrid-sdk-ts/pull/960) and review by @zaelgohary

### CODE REVIEW

**Comment by Mik-TF** [comment]
@xmonader 
Could you have a look?

Thanks.

**Comment by Mik-TF** [comment]
Since the [nextcloud weblet](https://playground.test.grid.tf/#/nextcloud) is now on the test net playground, I think we should merge this PR quickly.

@AhmedHanafy725 
@xmonader 
@ashraffouda 
@mohamedamer453 

Thanks!

**Comment by Mik-TF** [comment]
@AhmedHanafy725
@xmonader
@ashraffouda
@mohamedamer453

Could any of you guys have a look? Let me know if you have any questions or if changes are necessary.
If it's not a priority, I understand. I just want to know the status with this PR. 

Thanks!

**Comment by Mik-TF** [comment]
I updated the nextcloud docs to incorporate feedback from [here](https://github.com/threefoldtech/tfgrid-sdk-ts/issues/1047).

**Comment by Mik-TF** [comment]
@scottyeager and I are working on a new version of the weblet, that will enable gateway instead of simply IPv4. I will put this in draft until we have the latest version.

**Review by ramezsaeed — APPROVED** [review]

**Comment by Mik-TF** [comment]
Thanks @ramezsaeed 

Will soon add the info on the new weblet's feature (gateway for nextcloud). Then I will merge the PR.

**Pull request merged**
