### PR TITLE
Mycelium for Go, pulumi, javascript and Terraform

### PR DESCRIPTION
**Pull request by Mik-TF**
# Related Issue

- #617 

# Status

- WIP
  - TODO: once examples are updated with Mycelium support for all repos (terraform, pulumi, javascript, go)
     - we will be able to update the manual with the new example

# Work Done

- Added clear Mycelium guide link to all 4 sections (pulumi, javascript, terraform, go)
- Added Mycelium guide link and updated examples for TFROBOT and TFCMD

### CODE REVIEW

**Comment by Mik-TF** [comment]
@xmonader can you check this PR and let me know if you think we should merge it now?

As stated in #617, we could

- merge this PR as is now
- when other repos have updates on mycelium, we make another PR for info_grid and update with the latest info

OR, we wait until the other repos are updated and we merge this PR when we update info_grid with the updated links and content from the other repos.

Thanks.

**Comment by Mik-TF** [comment]
@xmonader please let me know what you think of the comment just above: do we merge now or wait? Thanks!!

**Comment by Mik-TF** [comment]
# Update

- Related issues are being worked on. When they are all closed, we can continue this PR and merge.

**Comment by Mik-TF** [comment]
# Update

- PR ready to be reviewed @xmonader @khaledyoussef24, thanks

**Review by khaledyoussef24 — APPROVED** [review]

**Pull request merged**
