### PR TITLE
Development dedicated nodefinder

### PR DESCRIPTION
**Pull request by Mik-TF**
# Related Issue

- #507 

# Work Done

- Removed dedicated node
- Updated node finder with new UI

### CODE REVIEW

**Comment by Mik-TF** [comment]
WIP: We need to add info on how to rent dedicated node now.

@zaelgohary

**Comment by khaledyoussef24** [comment]
may we add a photo for the reserve button of dedicated node in the node finder ?

**Comment by khaledyoussef24** [comment]
every thing else looks perfect, great job.

**Comment by Mik-TF** [comment]
> may we add a photo for the reserve button of dedicated node in the node finder ?

Done. Took the opportunity to put some of the dedicated node info as well as gpu node info. Updated the pictures with rentable toggle button too.

**Review by khaledyoussef24 — APPROVED** [review]
@Mik-TF Great Job is done here

**Pull request merged**
