### PR TITLE
updated grid deployment section to simplify future updates

### PR DESCRIPTION
**Pull request by Mik-TF**
# Related Issue

- https://github.com/threefoldtech/info_grid/issues/665

# Work Done

- Simplified the grid deployment section
  - We now only point to the grid_deployment docs to facilitate future updates
  - This means we can now focus on the grid_deployment docs and the manual won't need any updates.

### CODE REVIEW

**Comment by A-Harby** [comment]
I don't get ti, Why are we removing [grid_deployment_full_vm.md](https://github.com/threefoldtech/info_grid/pull/659/files#diff-59a105c075f91dfd7adfcd7f2417f90cb34d4fdd0a578959f1c41f11ccae4b3f) ?

**Comment by Mik-TF** [comment]
When I first wrote this section of the manual, it was before the TFGrid Full Stack procedures were documented on grid_deployment repo.

Just recently, @coesensbert completed all the docs for the full grid stack, not just the grid backend. I also made sure the docs were uniformized. See here: https://github.com/threefoldtech/grid_deployment/tree/development

So the idea is that the manual will point to the grid_deployment docs and we can just update that repo and the manual won't be out of sync.

If you think the manual docs have some relevant info, we can put it in the grid_deployment docs. But I think it'll be easier to maintain one set of docs, especially since the future grid guardians will need to host the grid stack, we will want as less confusion and as much clarity as possible on which set of docs to use.

I hope it's clear.

**Comment by A-Harby** [comment]
@Mik-TF Great since the same info is on the repo docs, only one would be enough.

Can you just fix the conflict.

**Comment by A-Harby** [comment]
Also, I notice that there's a lot of info missing, like creating a TFChain node and a lot of information and notes that wouldn't be there.

```
Generate a TFChain node key with subkey

Note: If you deploy the 3 network instances, you can use the same node key for all 3 networks. But it is recommended to use 3 different keys to facilitate management.
echo .nodekey_mainnet >> .gitignore
../../apps/subkey generate-node-key > .nodekey_mainnet
cat .nodekey_mainnet
```

**Review by A-Harby — APPROVED** [review]
lGTM

**Pull request merged**
