### PR TITLE
Development update links

### PR DESCRIPTION
**Pull request by Mik-TF**
* To answer the issue: https://github.com/threefoldtech/info_grid/issues/297

* Notes: Most of the links `` for the images in the threefold token buy and sell sections needed to be removed. For some reasons, the images have all disappeared.
* Removed mastodon section since the website https://getmastodon.threefold.io/ doesn't work anymore.
* Added testlodge section, it wasn't included in the summary but the file was present.

### CODE REVIEW

**Comment by Mik-TF** [comment]
@xmonader 
I set the priority to major since it was asked in today's meeting by @sabrinasadik  to be done ASAP. So if we can review within the next 2-3 days, it would be great.

Thanks!

**Comment by Mik-TF** [comment]
Around 58 links are left to be fixed.

**Comment by sabrinasadik** [comment]
@TullysInc pls follow up too

**Review by A-Harby — APPROVED** [review]
LGTM,
Old links were updated to newer ones or removed, and Mastadom was commented.

**Comment by TullysInc** [comment]
> @TullysInc pls follow up too

Mik and I are collaborating to cover ground across all literary archives, so Mik is managing the manual while support is taking over the website and others. I will be creating a ticket for the support task under the foundation repo.

**Comment by Mik-TF** [comment]
Thanks @A-Harby 

I did another commit to fix 59 more broken links. I will merge the PR and verify once more.
Once we verify all of the links manually, we can use the link checker for every new PR.

**Pull request merged**
