### PR TITLE
Added docs for gpu support.

### PR DESCRIPTION
**Pull request by Mahmoud-Emad**
### Related Issues
- https://github.com/threefoldtech/info_grid/issues/156

### Screenshots

- Playground
  - image
- Go, client,
  - image
- tfgrid-cli
  - image
- tf-chain
  - image
- dashboard
  - image

### CODE REVIEW

**Comment by Mik-TF** [comment]
@xmonader 
Something is weird in general with this whole workflow:

we have docs/ in .gitignore but still files get added in PR in the docs folder.
This shouldn't happen.

For this one, I can just remove the files in docs and force a push, then merge the PR. But ideally, we can have the proper flow for .gitignore so writers can only push the /src files.

**Comment by Mik-TF** [comment]
@Mahmoud-Emad 
Could you remove the file changes in the directory docs? So we could merge only changes in src.
Thanks!

**Comment by Mahmoud-Emad** [comment]
@Mik-TF, following up on [this issue](https://github.com/threefoldtech/info_grid/issues/173), it has been suggested to remove the docs directory from the development branch. The proposed approach is as follows: we remove the docs directory from the development branch, and subsequently, I will also remove it from my branch. When we merge the development branch into the master branch, the removal of the docs directory is expected to be reflected there. This aligns with the recommended course of action outlined in the issue. Please let me know your thoughts and if you have any additional considerations.

**Comment by Mik-TF** [comment]
Thanks @Mahmoud-Emad 
I removed docs in both dev branch and dev_gpu_support branch.

I will edit some small details on this PR then merge.

**Pull request merged**
