### PR TITLE
Merge development into master

### PR DESCRIPTION
**Pull request by Mahmoud-Emad**

### CODE REVIEW

**Review by mohamedamer453 — COMMENTED** [review]
This Pr contains docs related to the GPU support which shouldn't be merged to master yet.

**Comment by Mahmoud-Emad** [comment]
I'm gonna convert it to draft PR till we merge the GPU things into Mainnet

**Comment by Mahmoud-Emad** [comment]
@sasha-astiadi ask @xmonader

**Comment by Mik-TF** [comment]
I added a note to every page that discusses the the GPU support, to state that it is currently only for dev net.

Thus I ask: do you think it would be OK to merge dev to master in order to take into account newest changes, such as the mermaid feature?

Otherwise, we will have to wait until GPU is on main/test net before merging dev to master. Not ideal it seems.

Another possibility, is to make a branch out of dev, then remove the GPU files, then merge is branch into master.

Let me know what you guys think. Thanks!
@mohamedamer453 
@xmonader 
@ashraffouda 
@AhmedHanafy725

**Comment by Mik-TF** [comment]
@xmonader 

What do you think of this?

* We make a new branch from dev, called dev_gpu
  * to hold the gpu changes in dev_gpu until it is on main net
* We remove the mention of gpu in dev branch
* We merge dev to master (without the gpu branch)

**Comment by Mik-TF** [comment]
The gpu files are now available here: https://github.com/threefoldtech/info_grid/tree/development_gpu

So now dev branch doesn't have anything related to GPU.

I will thus set the PR as "ready for review".

When GPU is available on main net, we can merge dev-gpu to dev, and then dev to master.

**Pull request merged**
