### PR TITLE
Adding expose application's docs

### PR DESCRIPTION
**Pull request by maayarosama**
### Description
Adding expose docs

### Related Issues

- https://github.com/threefoldtech/tfgrid-sdk-ts/issues/3178

### CODE REVIEW

**Review by Mik-TF — APPROVED** [review]
LGTM.

Added the file in summary.md so we can access it on the manual.

Note: We should only merge the PR once the app is at least on devnet.

**Review by khaledyoussef24 — APPROVED** [review]

**Comment by khaledyoussef24** [comment]
shall we add images from the manage domains also ?

**Comment by Mik-TF** [comment]
@maayarosama What do you think of Khaled's proposition? We can make a new PR to add manage domain pictures.

**Comment by maayarosama** [comment]
> @maayarosama What do you think of Khaled's proposition? We can make a new PR to add manage domain pictures.

There's no manage domains feature in expose solution, it's in full vm solution. I suggest adding the picture to the fullvm docs

**Comment by Mik-TF** [comment]
We have a section showing how to manage the domains, which is valid for both micro and full VMs: https://www.manual.dev.grid.tf/documentation/dashboard/solutions/add_domain.html

@khaledyoussef24 I think this is sufficient. What do you think?

**Comment by khaledyoussef24** [comment]
Yes, this is more than enough

**Pull request merged**
