### PR TITLE
gitea basics guide

### PR DESCRIPTION
**Pull request by Mik-TF**
# Work Done

- Added guide on how to use Gitea
- Gitea in general
- Gitea API

# Related Issue

- Gitea soon on the dashboard! see #590

### CODE REVIEW

**Comment by khaledyoussef24** [comment]
blocked on https://github.com/threefoldtech/tfgrid-sdk-ts/issues/2015

**Comment by Mik-TF** [comment]
@khaledyoussef24 I think this one should be blocked (but it's in draft for exactly this reason): https://github.com/threefoldtech/info_grid/pull/592

For this guide, I present it as a companion to the GitHub basics guide: it shows how to use the platform, it's not about the Dashboard Gitea app.

**Review by khaledyoussef24 — APPROVED** [review]
yes you are right ,this can be merged sorry the delay @Mik-TF

**Comment by Mik-TF** [comment]
Absolutely no problem! Thanks for merging and have a good week :)

**Pull request merged**
